import {
  SvgAlarm,
  SvgAlarmChecked,
  SvgAlarmMinus,
  SvgAlarmNo,
  SvgAlarmPlus,
  SvgAlarmSnooze,
  SvgBarChart,
  SvgBook,
  SvgBookmark,
  SvgBookmarkAdd,
  SvgBookmarkNo,
  SvgBookmarks,
  SvgBox,
  SvgBrowser,
  SvgBrowserNo,
  SvgBrush,
  SvgCalculator,
  SvgCalendar,
  SvgCalendarChecked,
  SvgCalendarCreate,
  SvgCalendarDates,
  SvgCalendarDelete,
  SvgCalendarMinus,
  SvgCalendarPlus,
  SvgCamera,
  SvgCameraCreate,
  SvgCameraNo,
  SvgCase,
  SvgCheckMark,
  SvgCheckMarks,
  SvgCircle,
  SvgCircleBlock,
  SvgCircleChecked,
  SvgCircleMenu,
  SvgCircleMinus,
  SvgCircleMoreHorizontal,
  SvgCircleMoreVertical,
  SvgCirclePlus,
  SvgCircleStar,
  SvgCircleX,
  SvgClearStyle,
  SvgCopy,
  SvgCut,
  SvgDashboard,
  SvgDelete,
  SvgDownload,
  SvgDownloadBold,
  SvgDrop,
  SvgExternalLink,
  SvgEye,
  SvgEyeNo,
  SvgFlag,
  SvgFlame,
  SvgGlasses,
  SvgGlobe,
  SvgGlobeNo,
  SvgGooglelogo,
  SvgHeart,
  SvgHeartNo,
  SvgHome,
  SvgImage,
  SvgInbox,
  SvgLaughing,
  SvgLayers,
  SvgLightning,
  SvgLightningNo,
  SvgLink,
  SvgLinkNo,
  SvgList,
  SvgMail,
  SvgMaximize,
  SvgMenu,
  SvgMenuDots,
  SvgMic,
  SvgMicNo,
  SvgMinimize,
  SvgMinus,
  SvgMoreHorizontal,
  SvgMoreVertical,
  SvgNeutral,
  SvgNewspaper,
  SvgOptions,
  SvgPaperclip,
  SvgPaperclipNo,
  SvgPencilCreate,
  SvgPencilEdit,
  SvgPlus,
  SvgPresentation,
  SvgPrinter,
  SvgPulse,
  SvgSad,
  SvgScan,
  SvgScreenshot,
  SvgSearch,
  SvgSend,
  SvgSettings,
  SvgShare,
  SvgShareArrow,
  SvgShocked,
  SvgSmiled,
  SvgStar,
  SvgStarNo,
  SvgSticker,
  SvgStopwatch,
  SvgTable,
  SvgTextAlignCenter,
  SvgTextAlignJustify,
  SvgTextAlignLeft,
  SvgTextAlignRight,
  SvgTextBgcolor,
  SvgTextBold,
  SvgTextColor,
  SvgTextItalic,
  SvgTextUnderline,
  SvgThumbsDown,
  SvgThumbsUp,
  SvgTime,
  SvgTimeHistory,
  SvgTimer,
  SvgToggleLeft,
  SvgToggleRight,
  SvgTrash,
  SvgTrashEmpty,
  SvgUser,
  SvgVideo,
  SvgVideoNo,
  SvgWatch,
  SvgZoomIn,
  SvgZoomOut,
} from './Generated';

export const svgMap = {
  alarm: SvgAlarm,
  'alarm-checked': SvgAlarmChecked,
  'alarm-minus': SvgAlarmMinus,
  'alarm-no': SvgAlarmNo,
  'alarm-plus': SvgAlarmPlus,
  'alarm-snooze': SvgAlarmSnooze,
  'bar-chart': SvgBarChart,
  book: SvgBook,
  bookmark: SvgBookmark,
  'bookmark-add': SvgBookmarkAdd,
  'bookmark-no': SvgBookmarkNo,
  bookmarks: SvgBookmarks,
  box: SvgBox,
  browser: SvgBrowser,
  'browser-no': SvgBrowserNo,
  brush: SvgBrush,
  calculator: SvgCalculator,
  calendar: SvgCalendar,
  'calendar-checked': SvgCalendarChecked,
  'calendar-create': SvgCalendarCreate,
  'calendar-dates': SvgCalendarDates,
  'calendar-delete': SvgCalendarDelete,
  'calendar-minus': SvgCalendarMinus,
  'calendar-plus': SvgCalendarPlus,
  camera: SvgCamera,
  'camera-create': SvgCameraCreate,
  'camera-no': SvgCameraNo,
  case: SvgCase,
  'check-mark': SvgCheckMark,
  'check-marks': SvgCheckMarks,
  circle: SvgCircle,
  'circle-block': SvgCircleBlock,
  'circle-checked': SvgCircleChecked,
  'circle-menu': SvgCircleMenu,
  'circle-minus': SvgCircleMinus,
  'circle-more-horizontal': SvgCircleMoreHorizontal,
  'circle-more-vertical': SvgCircleMoreVertical,
  'circle-plus': SvgCirclePlus,
  'circle-star': SvgCircleStar,
  'circle-x': SvgCircleX,
  'clear-style': SvgClearStyle,
  copy: SvgCopy,
  cut: SvgCut,
  dashboard: SvgDashboard,
  delete: SvgDelete,
  download: SvgDownload,
  'download-bold': SvgDownloadBold,
  drop: SvgDrop,
  'external-link': SvgExternalLink,
  eye: SvgEye,
  'eye-no': SvgEyeNo,
  flag: SvgFlag,
  flame: SvgFlame,
  glasses: SvgGlasses,
  globe: SvgGlobe,
  'globe-no': SvgGlobeNo,
  googlelogo: SvgGooglelogo,
  heart: SvgHeart,
  'heart-no': SvgHeartNo,
  home: SvgHome,
  image: SvgImage,
  inbox: SvgInbox,
  laughing: SvgLaughing,
  layers: SvgLayers,
  lightning: SvgLightning,
  'lightning-no': SvgLightningNo,
  link: SvgLink,
  'link-no': SvgLinkNo,
  list: SvgList,
  mail: SvgMail,
  maximize: SvgMaximize,
  menu: SvgMenu,
  'menu-dots': SvgMenuDots,
  mic: SvgMic,
  'mic-no': SvgMicNo,
  minimize: SvgMinimize,
  minus: SvgMinus,
  'more-horizontal': SvgMoreHorizontal,
  'more-vertical': SvgMoreVertical,
  neutral: SvgNeutral,
  newspaper: SvgNewspaper,
  options: SvgOptions,
  paperclip: SvgPaperclip,
  'paperclip-no': SvgPaperclipNo,
  'pencil-create': SvgPencilCreate,
  'pencil-edit': SvgPencilEdit,
  plus: SvgPlus,
  presentation: SvgPresentation,
  printer: SvgPrinter,
  pulse: SvgPulse,
  sad: SvgSad,
  scan: SvgScan,
  screenshot: SvgScreenshot,
  search: SvgSearch,
  send: SvgSend,
  settings: SvgSettings,
  share: SvgShare,
  'share-arrow': SvgShareArrow,
  shocked: SvgShocked,
  smiled: SvgSmiled,
  star: SvgStar,
  'star-no': SvgStarNo,
  sticker: SvgSticker,
  stopwatch: SvgStopwatch,
  table: SvgTable,
  'text-align-center': SvgTextAlignCenter,
  'text-align-justify': SvgTextAlignJustify,
  'text-align-left': SvgTextAlignLeft,
  'text-align-right': SvgTextAlignRight,
  'text-bgcolor': SvgTextBgcolor,
  'text-bold': SvgTextBold,
  'text-color': SvgTextColor,
  'text-italic': SvgTextItalic,
  'text-underline': SvgTextUnderline,
  'thumbs-down': SvgThumbsDown,
  'thumbs-up': SvgThumbsUp,
  time: SvgTime,
  'time-history': SvgTimeHistory,
  timer: SvgTimer,
  'toggle-left': SvgToggleLeft,
  'toggle-right': SvgToggleRight,
  trash: SvgTrash,
  'trash-empty': SvgTrashEmpty,
  user: SvgUser,
  video: SvgVideo,
  'video-no': SvgVideoNo,
  watch: SvgWatch,
  'zoom-in': SvgZoomIn,
  'zoom-out': SvgZoomOut,
};

export type IconName = keyof typeof svgMap;
