service:
  name: CoHope-app-server

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-websockets-plugin

custom:
  env: ${file(./env.yml):${opt:stage, self:provider.stage}}
  serverless-offline:
    port: 7000
    websocketPort: 7001
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true # Node modules configuration for packaging
  websocketApiRouteSelectionExpression: $request.body.action

provider:
  name: aws
  stage: dev # default is dev
  region: ap-northeast-2
  runtime: nodejs10.x
  environment:
    APOLLO_KEY: ${self:custom.env.APOLLO_KEY}
    ENV: ${self:custom.env.NODE_ENV}
    KEY_OF_FUCKING_SECRET: ${self:custom.env.KEY_OF_FUCKING_SECRET}
    DATABASE: ${self:custom.env.DATABASE}
    DATABASE_USERNAME: ${self:custom.env.DATABASE_USERNAME}
    DATABASE_PASSWORD: ${self:custom.env.DATABASE_PASSWORD}
    DATABASE_PORT: ${self:custom.env.DATABASE_PORT}
    DATABASE_URL: ${self:custom.env.DATABASE_URL}
    GOOGLE_SECRET: ${self:custom.env.GOOGLE_SECRET}
    GOOGLE_CLIENT: ${self:custom.env.GOOGLE_CLIENT}
  timeout: 30

functions:
  gql:
    handler: src/index.handler
    events:
      - http:
          method: team
          cors: true
          path: graphql
      - http:
          method: get
          cors: true
          path: graphql
  loginOrRegister:
    handler: src/http/index.loginOrRegister
    events:
      - http:
          method: team
          cors: true
          path: login-or-register
  # websocketHandler:
  #   handler: dist/src/socket/index.connect
  #   events:
  #     - websocket:
  #         routeKey: $connect
  #     - websocket:
  #         routeKey: $disconnect
