export enum UserActionTypes {
  REGISTER = 'REGISTER',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAILURE = 'REGISTER_FAILURE',

  LOGIN = 'LOGIN',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',

  GET_MY_INFO = 'GET_MY_INFO',
  GET_MY_INFO_SUCCESS = 'GET_MY_INFO_SUCCESS',
  GET_MY_INFO_FAILURE = 'GET_MY_INFO_FAILURE',

  LOGOUT = 'LOGOUT',
}
